import { describe, it, expect } from 'vitest';
import ExcelJS from 'exceljs';
import {
  writeInfoSheet, setInfoSheetCount, formatGeneratedAt, INFO_ROW, INFO_SHEET_NAME,
} from '@/lib/backup/info-sheet';

const INFO = {
  businessName: 'Khaliq Oil',
  businessId: '11111111-2222-3333-4444-555555555555',
  generatedAt: new Date('2026-08-09T17:22:00Z'), // 10:22 PM in Karachi
  period: 'All Time',
  generatedBy: 'Ahmad Naveed',
};

/** Write the sheet, save to a real .xlsx buffer, read it back. */
async function roundTrip(sheetCount = 7): Promise<ExcelJS.Worksheet> {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet(INFO_SHEET_NAME);
  writeInfoSheet(ws, INFO);
  setInfoSheetCount(ws, sheetCount);

  const buffer = await wb.xlsx.writeBuffer();
  const reopened = new ExcelJS.Workbook();
  await reopened.xlsx.load(buffer);
  const sheet = reopened.getWorksheet(INFO_SHEET_NAME);
  if (!sheet) throw new Error('Info sheet missing from the written workbook');
  return sheet;
}

describe('info sheet', () => {
  it('writes exactly two cells on the Sheet Count row, so nothing can sit in C', async () => {
    // Reported five times now. The cell-value check below can be argued with
    // ("maybe it reads B but writes C"); a count of the cells the row actually
    // holds cannot — a value in C would make this three.
    const ws = await roundTrip(23);
    const row = ws.getRow(INFO_ROW.sheetCount);
    expect(row.actualCellCount).toBe(2);
    expect(row.cellCount).toBe(2);
  });

  it('puts Sheet Count in column B, never column C', async () => {
    const ws = await roundTrip(23);
    expect(ws.getCell(`A${INFO_ROW.sheetCount}`).value).toBe('Sheet Count');
    expect(ws.getCell(`B${INFO_ROW.sheetCount}`).value).toBe(23);
    expect(ws.getCell(`C${INFO_ROW.sheetCount}`).value).toBeNull();
  });

  it('keeps every fact in the Key/Value columns A and B', async () => {
    const ws = await roundTrip();
    for (const row of Object.values(INFO_ROW)) {
      expect(typeof ws.getCell(`A${row}`).value).toBe('string');
      expect(ws.getCell(`B${row}`).value).not.toBeNull();
      expect(ws.getCell(`C${row}`).value).toBeNull();
    }
  });

  it('lays the facts out in the documented order', async () => {
    const ws = await roundTrip();
    expect(ws.getCell('A1').value).toBe('Key');
    expect(ws.getCell('B1').value).toBe('Value');
    expect(ws.getCell(`A${INFO_ROW.business}`).value).toBe('Business');
    expect(ws.getCell(`B${INFO_ROW.business}`).value).toBe('Khaliq Oil');
    expect(ws.getCell(`B${INFO_ROW.businessId}`).value).toBe(INFO.businessId);
    expect(ws.getCell(`A${INFO_ROW.period}`).value).toBe('Period');
    expect(ws.getCell(`B${INFO_ROW.period}`).value).toBe('All Time');
    expect(ws.getCell(`A${INFO_ROW.generatedBy}`).value).toBe('Generated By');
    expect(ws.getCell(`B${INFO_ROW.generatedBy}`).value).toBe(INFO.generatedBy);
  });

  it('renders Generated At as Karachi wall-clock', () => {
    expect(formatGeneratedAt(INFO.generatedAt)).toBe('09 Aug 2026, 10:22 PM PKT');
  });
});
