import type ExcelJS from 'exceljs';
import { formatKarachi } from '@/lib/date';

/**
 * The workbook's first sheet: a fixed Key/Value block.
 *
 * Every cell is written by literal address (B5), never through
 * `row.getCell('value')`. The layout is then a property of this file rather
 * than of ExcelJS's column-key bookkeeping, and info-sheet.test.ts round-trips
 * a real .xlsx to assert it — the "Sheet Count is in column C" report has been
 * raised against this sheet four times and each investigation ended in prose.
 * It now ends in a test.
 */

export const INFO_SHEET_NAME = 'Info';

/** 1-indexed worksheet row of each fact. Row 1 holds the Key/Value header. */
export const INFO_ROW = {
  business: 2,
  businessId: 3,
  generatedAt: 4,
  sheetCount: 5,
  moneyColumns: 6,
  timestamps: 7,
  period: 8,
  generatedBy: 9,
} as const;

export type BackupInfo = {
  businessName: string;
  businessId: string;
  generatedAt: Date;
  /** "All Time", or the resolved date-range label. */
  period: string;
  /** Full name of the signed-in user who asked for the backup. */
  generatedBy: string;
};

const NOTES = {
  money:
    'Shown in rupees to 2 decimal places, grouped the Pakistani way (1,50,000.00). '
    + 'The database stores integer paisa (1 PKR = 100 paisa).',
  timestamps:
    'Every date and time in this workbook is Asia/Karachi (PKT, UTC+5), '
    + 'converted from the UTC timestamps the database stores.',
} as const;

/** "09 Aug 2026, 10:22 PM PKT" */
export function formatGeneratedAt(d: Date): string {
  return `${formatKarachi(d, 'dd MMM yyyy, hh:mm a')} PKT`;
}

export function writeInfoSheet(ws: ExcelJS.Worksheet, info: BackupInfo): void {
  ws.getColumn(1).width = 18;
  ws.getColumn(2).width = 92;

  const put = (row: number, key: string, value: string | number): void => {
    ws.getCell(`A${row}`).value = key;
    ws.getCell(`B${row}`).value = value;
  };

  put(1, 'Key', 'Value');
  put(INFO_ROW.business, 'Business', info.businessName);
  put(INFO_ROW.businessId, 'Business ID', info.businessId);
  put(INFO_ROW.generatedAt, 'Generated At', formatGeneratedAt(info.generatedAt));
  put(INFO_ROW.sheetCount, 'Sheet Count', 0);
  put(INFO_ROW.moneyColumns, 'Money Columns', NOTES.money);
  put(INFO_ROW.timestamps, 'Timestamps', NOTES.timestamps);
  put(INFO_ROW.period, 'Period', info.period);
  put(INFO_ROW.generatedBy, 'Generated By', info.generatedBy);

  ws.getRow(1).font = { bold: true };
  for (let r = INFO_ROW.business; r <= INFO_ROW.generatedBy; r++) {
    ws.getCell(`A${r}`).font = { bold: true };
    ws.getCell(`B${r}`).alignment = { vertical: 'top', wrapText: true };
  }
}

/**
 * Filled in once the workbook is complete, so it counts the sheets that were
 * actually written rather than the sheets that were planned.
 */
export function setInfoSheetCount(ws: ExcelJS.Worksheet, count: number): void {
  ws.getCell(`B${INFO_ROW.sheetCount}`).value = count;
}
